### ISSUE TITLE
Lack of `next page` in readthedocs makes reading through the documentation excessively irritating

### ISSUE THREAD

**Issue by deliciouslytyped** [rocky/remake#120]
I apologize in advance if my tone comes off harsh.

I would like to read the documentation at [https://remake.readthedocs.io/en/latest/](https://remake.readthedocs.io/en/latest/) cover to cover, but I see no way to navigate the documentation other than clumsily trying to click through various sub-tables-of-contents scattered over the documentation.
 
If there was a central TOC that would at least help, but what I would really like is if I could just have a way to go to the next section when I reach the bottom of the page.

Can anything be done about this?

Someone please explain to me how and why I am the idiot, and don't know how to use readthedocs.

**Comment by deliciouslytyped** [comment]
As a workaround one can look at the PDF render https://remake.readthedocs.io/_/downloads/en/latest/pdf/ , though the browser version looks nicer I think.

**Comment by rocky** [comment]
Thanks for your comments, @deliciouslytyped ! 

Let me tell you a story about how this code got written. I thought, hey, GNU Make is really cool but I wanted to ..., and thought wouldn't it be nice if, ...

Of course, I was hoping someone else would find value and interest in doing this and get it done. After a year of no takers, I rolled up my sleeves and did those things I found useful. 

I don't have a ready answer to your question or how to address your desire. It seems like a reasonable thing to want though; it's not something that bothers me. My workflow is a bit different.

Perhaps if you asked on [stack overflow](https://stackoverflow.com/) or some forum like that you might get suggestions for how to improve the situation that might be to your liking.  Or perhaps someone will read the issue here and comment. (But in my experience I haven't seen much of this kind of thing, especially for this particular project.) 

And then if you take the next step and implement the desired solution, and it it requires a change here and seems generally applicable I'll be happy to incorporate it! (And even if I don't, there can be your fork of this, just as I have a fork of GNU make).

**Comment by deliciouslytyped** [comment]
I did not state this and I would like to after the fact;
I am very happy this tool exists and has branches for the major gmake versions.

This is more an issue with readthedocs than anything else.

**Comment by boretom** [comment]
The 'next' and 'previous' button seem to be a feature of the themes, and differ from theme to theme.

I did check the alabaster theme (which is used for remake) and according to the [doc](https://alabaster.readthedocs.io/en/latest/customization.html#theme-options) you can add `'show_relbars' : 'true'` to the `html_theme_options` in `doc/readthedocs/conf.py` to enable them. There are a few additional options to enable only the links before or after the text, or enable them in the sidebar.

Haven't checked the outcome myself yet and I'll only have time sometime ofter next week.

**Addition**: I gave it a quick go and these features where only added in alabaster 0.7.11. On my latest Linux Mint alabaster 0.7.8 is included and therefore the latest version (which is from 2018) would have to included manually.

It would look something like this:
![Screenshot alabaster with next prev](https://user-images.githubusercontent.com/52218/134799119-83ea7af0-efcd-40cc-a6ac-bfe92b14d627.jpg)
)

**Comment by deliciouslytyped** [comment]
LGTM I think.
