### ISSUE TITLE
Invalid JSON profile output 

### ISSUE THREAD

**Issue by uvatbc** [rocky/remake#130]
I wrote a simple Makefile to demonstrate the problem:
```
.PHONY: all step1 step2

all: step1 step2
        echo All

step1:
        echo Step 1

step2:
        echo Step 2

test1: # Succeeds
        -rm *.json
        remake --profile=json all -j
        set -x ; find . -type f -maxdepth 1 -name '*.json' | while read line ; do jq . $$line ; done

test2: # Fails because of invalid json
        -rm *.json
        remake --profile=json step2 step2 -j
        set -x ; find . -type f -maxdepth 1 -name '*.json' | while read line ; do jq . $$line ; done
```

There are two targets to test the makefile under remake: `test1` and `test2`.    
`test1` works correctly, and the JSON is valid. `test2` fails because the JSON profile data generated by remake is invalid.

**Comment by rocky** [comment]
@Arrowbox - this is related to a feature you added [to support profiling output as JSON](https://github.com/rocky/remake/pull/128). Would you take a look at and advise? 

Attached are two JSON files (tagged as `.txt` since github doesn't allow `.json` attachments) 

[build.3234215.txt](https://github.com/rocky/remake/files/7835885/build.3234215.txt)
[build.3234294.txt](https://github.com/rocky/remake/files/7835886/build.3234294.txt)

From the above, it looks like and extra `]`, is output in: 

```
	"entry":[
		"step2",
	],
		"step2"
	],
```

Maybe something is getting confused when there are multiple targets as it `remake --profile=json step2 step2`? 

@uvatbc - also feel free jump into the code for fixing. 

This is something I probably won't spend much time looking at.

**Comment by Arrowbox** [comment]
I'll take a look and see what I find.

**Comment by Arrowbox** [comment]
End bracket was inside the loop rather than outside. PR up with the fix.

**Comment by rocky** [comment]
@uvatbc I tried this on the example and it works. If it works for you close the issue.

**Comment by uvatbc** [comment]
Confirmed on top of trunk.
Thanks so much!
